@echo off
echo " BloatWrek can help you clean bloatware from funtouch os besides some unwanted google stuff"
cd %cd%/adb
adb.exe devices
adb.exe wait-for-device >NUL 2>NUL
adb.exe devices -l 
echo " Clean your phone " ;
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.betterbug
adb.exe shell pm uninstall -k --user 0 android.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 android.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 android.autoinstalls.config.google.nexus
adb.exe shell pm uninstall -k --user 0 com.android.bips
adb.exe shell pm uninstall -k --user 0 com.android.bips.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.bluetoothmidiservice
adb.exe shell pm uninstall -k --user 0 com.android.bookmarkprovider
adb.exe shell pm uninstall -k --user 0 com.android.cameraextensions
adb.exe shell pm uninstall -k --user 0 com.android.captiveportallogin.overlay
adb.exe shell pm uninstall -k --user 0 com.android.carrierdefaultapp
adb.exe shell pm uninstall -k --user 0 com.android.cellbroadcastreceiver
adb.exe shell pm uninstall -k --user 0 com.android.cellbroadcastreceiver.overlay.pixel
adb.exe shell pm uninstall -k --user 0 com.android.cellbroadcastservice.overlay.pixel
adb.exe shell pm uninstall -k --user 0 com.android.certinstaller
adb.exe shell pm uninstall -k --user 0 com.android.companiondevicemanager
adb.exe shell pm uninstall -k --user 0 com.android.cts.ctsshim
adb.exe shell pm uninstall -k --user 0 com.android.cts.priv.ctsshim
adb.exe shell pm uninstall -k --user 0 com.android.dreams.basic
adb.exe shell pm uninstall -k --user 0 com.android.dynsystem
adb.exe shell pm uninstall -k --user 0 com.android.egg
adb.exe shell pm uninstall -k --user 0 com.android.emergency
adb.exe shell pm uninstall -k --user 0 com.android.hbmsvmanager.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.hotwordenrollment.okgoogle
adb.exe shell pm uninstall -k --user 0 com.android.hotwordenrollment.xgoogle
adb.exe shell pm uninstall -k --user 0 com.android.htmlviewer
adb.exe shell pm uninstall -k --user 0 com.android.imsserviceentitlement
adb.exe shell pm uninstall -k --user 0 com.android.inputdevices
adb.exe shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.avoidAppsInCutout
adb.exe shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.corner
adb.exe shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.double
adb.exe shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.hole
adb.exe shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.noCutout
adb.exe shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.tall
adb.exe shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.waterfall
adb.exe shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.threebutton
adb.exe shell pm uninstall -k --user 0 com.android.managedprovisioning
adb.exe shell pm uninstall -k --user 0 com.android.managedprovisioning.overlay
adb.exe shell pm uninstall -k --user 0 com.android.mms.service
adb.exe shell pm uninstall -k --user 0 com.android.networkstack.overlay
adb.exe shell pm uninstall -k --user 0 com.android.nfc
adb.exe shell pm uninstall -k --user 0 com.android.nfc.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.nfc.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 com.android.omadm.service
adb.exe shell pm uninstall -k --user 0 com.android.omadm.service.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.omadm.service.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 com.android.ons
adb.exe shell pm uninstall -k --user 0 com.android.ons.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 com.android.pacprocessor
adb.exe shell pm uninstall -k --user 0 com.android.phone.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.phone.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 com.android.printspooler
adb.exe shell pm uninstall -k --user 0 com.android.providers.contacts.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.providers.media.overlay.pixel
adb.exe shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks
adb.exe shell pm uninstall -k --user 0 com.android.providers.settings.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.providers.telephony.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.providers.userdictionary
adb.exe shell pm uninstall -k --user 0 com.android.proxyhandler
adb.exe shell pm uninstall -k --user 0 com.android.remoteprovisioner
adb.exe shell pm uninstall -k --user 0 com.android.safetyregulatoryinfo
adb.exe shell pm uninstall -k --user 0 com.android.safetyregulatoryinfo.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.sdm.plugins.connmo
adb.exe shell pm uninstall -k --user 0 com.android.sdm.plugins.dcmo
adb.exe shell pm uninstall -k --user 0 com.android.sdm.plugins.diagmon
adb.exe shell pm uninstall -k --user 0 com.android.server.telecom.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.settings.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.settings.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 com.android.settings.overlay.gb7n6
adb.exe shell pm uninstall -k --user 0 com.android.settings.overlay.oriole
adb.exe shell pm uninstall -k --user 0 com.android.settings.overlay.pixel2021
adb.exe shell pm uninstall -k --user 0 com.android.simappdialog
adb.exe shell pm uninstall -k --user 0 com.android.simappdialog.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.stk
adb.exe shell pm uninstall -k --user 0 com.android.systemui.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.systemui.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 com.android.systemui.plugin.globalactions.wallet
adb.exe shell pm uninstall -k --user 0 com.android.traceur
adb.exe shell pm uninstall -k --user 0 com.android.traceur.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.android.traceur.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 com.android.wallpaper.livepicker
adb.exe shell pm uninstall -k --user 0 com.android.yadayada
adb.exe shell pm uninstall -k --user 0 com.customermobile.preload.vzw
adb.exe shell pm uninstall -k --user 0 com.google.ambient.streaming
adb.exe shell pm uninstall -k --user 0 com.google.android.accessibility.soundamplifier
adb.exe shell pm uninstall -k --user 0 com.google.android.adservices.api
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.accessibility.voiceaccess
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.carrier.carrierwifi
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.carrier.log
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.cbrsnetworkmonitor
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.diagnosticstool
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.dreamliner
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.gcs
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.helprtc
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.internal.betterbug
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.restore
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.safetyhub
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.scone
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.scone.overlays
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.security.securityhub
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.tips
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.turbo
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.wallpaper.pixel
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.wearables.maestro.companion
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.wellbeing
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.work.clouddpc
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.work.oobconfig
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.youtube.music
adb.exe shell pm uninstall -k --user 0 com.google.android.as
adb.exe shell pm uninstall -k --user 0 com.google.android.as.oss
adb.exe shell pm uninstall -k --user 0 com.google.android.captiveportallogin
adb.exe shell pm uninstall -k --user 0 com.google.android.carrier
adb.exe shell pm uninstall -k --user 0 com.google.android.carrierlocation
adb.exe shell pm uninstall -k --user 0 com.google.android.carriersetup
adb.exe shell pm uninstall -k --user 0 com.google.android.cellbroadcastreceiver
adb.exe shell pm uninstall -k --user 0 com.google.android.cellbroadcastservice
adb.exe shell pm uninstall -k --user 0 com.google.android.compos.payload
adb.exe shell pm uninstall -k --user 0 com.google.android.configupdater
adb.exe shell pm uninstall -k --user 0 com.google.android.connectivity.resources.overlay
adb.exe shell pm uninstall -k --user 0 com.google.android.connectivitythermalpowermanager
adb.exe shell pm uninstall -k --user 0 com.google.android.documentsui.theme.pixel
adb.exe shell pm uninstall -k --user 0 com.google.android.dreamlinerupdater
adb.exe shell pm uninstall -k --user 0 com.google.android.euicc
adb.exe shell pm uninstall -k --user 0 com.google.android.factoryota
adb.exe shell pm uninstall -k --user 0 com.google.android.feedback
adb.exe shell pm uninstall -k --user 0 com.google.android.flipendo
adb.exe shell pm uninstall -k --user 0 com.google.android.flipendo.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.google.android.flipendo.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 com.google.android.gms.location.history
adb.exe shell pm uninstall -k --user 0 com.google.android.gms.supervision
adb.exe shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb.exe shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox.nga_resources
adb.exe shell pm uninstall -k --user 0 com.google.android.grilservice
adb.exe shell pm uninstall -k --user 0 com.google.android.hardwareinfo
adb.exe shell pm uninstall -k --user 0 com.google.android.hotspot2.osulogin
adb.exe shell pm uninstall -k --user 0 com.google.android.ims
adb.exe shell pm uninstall -k --user 0 com.google.android.iwlan
adb.exe shell pm uninstall -k --user 0 com.google.android.markup
adb.exe shell pm uninstall -k --user 0 com.google.android.marvin.talkback
adb.exe shell pm uninstall -k --user 0 com.google.android.nearby.halfsheet
adb.exe shell pm uninstall -k --user 0 com.google.android.networkstack.tethering.overlay2021
adb.exe shell pm uninstall -k --user 0 com.google.android.odad
adb.exe shell pm uninstall -k --user 0 com.google.android.ondevicepersonalization.services
adb.exe shell pm uninstall -k --user 0 com.google.android.onetimeinitializer
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.bugreporthandleruserbuildconfig
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.googleconfig
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.googlewebview
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.permissioncontroller
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.pixelconfig2018
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.pixelconfig2019
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.pixelconfig2019midyear
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.pixelconfig2021
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.pixelconfigcommon
adb.exe shell pm uninstall -k --user 0 com.google.android.overlay.udfpsoverlay
adb.exe shell pm uninstall -k --user 0 com.google.android.partnersetup
adb.exe shell pm uninstall -k --user 0 com.google.android.pixel.setupwizard
adb.exe shell pm uninstall -k --user 0 com.google.android.pixel.setupwizard.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.google.android.pixel.setupwizard.overlay
adb.exe shell pm uninstall -k --user 0 com.google.android.pixel.setupwizard.overlay2019
adb.exe shell pm uninstall -k --user 0 com.google.android.pixel.setupwizard.overlay2021
adb.exe shell pm uninstall -k --user 0 com.google.android.pixelnfc
adb.exe shell pm uninstall -k --user 0 com.google.android.printservice.recommendation
adb.exe shell pm uninstall -k --user 0 com.google.android.projection.gearhead
adb.exe shell pm uninstall -k --user 0 com.google.android.safetycenter.resources
adb.exe shell pm uninstall -k --user 0 com.google.android.setupwizard
adb.exe shell pm uninstall -k --user 0 com.google.android.storagemanager
adb.exe shell pm uninstall -k --user 0 com.google.android.storagemanager.auto_generated_rro_product__
adb.exe shell pm uninstall -k --user 0 com.google.android.storagemanager.auto_generated_rro_vendor__
adb.exe shell pm uninstall -k --user 0 com.google.android.systemui.gxoverlay
adb.exe shell pm uninstall -k --user 0 com.google.android.tag
adb.exe shell pm uninstall -k --user 0 com.google.android.tetheringentitlement
adb.exe shell pm uninstall -k --user 0 com.google.android.tts
adb.exe shell pm uninstall -k --user 0 com.google.android.turboadapter
adb.exe shell pm uninstall -k --user 0 com.google.android.uvexposurereporter
adb.exe shell pm uninstall -k --user 0 com.google.android.videos
adb.exe shell pm uninstall -k --user 0 com.google.android.virtualmachine.res
adb.exe shell pm uninstall -k --user 0 com.google.android.wfcactivation
adb.exe shell pm uninstall -k --user 0 com.google.ar.core
adb.exe shell pm uninstall -k --user 0 com.google.audio.hearing.visualization.accessibility.scribe
adb.exe shell pm uninstall -k --user 0 com.google.euiccpixel
adb.exe shell pm uninstall -k --user 0 com.google.euiccpixel.overlay.gs101
adb.exe shell pm uninstall -k --user 0 com.google.euiccpixel.permissions
adb.exe shell pm uninstall -k --user 0 com.google.mainline.adservices
adb.exe shell pm uninstall -k --user 0 com.google.omadm.trigger
adb.exe shell pm uninstall -k --user 0 com.google.pixel.livewallpaper
adb.exe shell pm uninstall -k --user 0 com.google.RilConfigService
adb.exe shell pm uninstall -k --user 0 com.google.SSRestartDetector
adb.exe shell pm uninstall -k --user 0 com.samsung.slsi.telephony.oem.oemrilhookservice
adb.exe shell pm uninstall -k --user 0 com.samsung.slsi.telephony.oemril
adb.exe shell pm uninstall -k --user 0 com.shannon.imsservice
adb.exe shell pm uninstall -k --user 0 com.shannon.rcsservice
adb.exe shell pm uninstall -k --user 0 com.verizon.llkagent
adb.exe shell pm uninstall -k --user 0 com.verizon.mips.services
adb.exe shell pm uninstall -k --user 0 com.verizon.services
adb.exe shell pm uninstall -k --user 0 com.vzw.apnlib
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.docs
adb.exe shell pm uninstall -k --user 0 com.android.musicfx
adb.exe shell pm uninstall -k --user 0 com.android.theme.font.notoserifsource
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.camera.services
adb.exe shell pm uninstall -k --user 0 com.shannon.qualifiednetworksservice
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.recorder
adb.exe shell pm uninstall -k --user 0 com.android.se
adb.exe shell pm uninstall -k --user 0 com.google.mainline.telemetry
adb.exe shell pm uninstall -k --user 0 com.android.uwb.resources
adb.exe shell pm uninstall -k --user 0 com.android.exchange
adb.exe shell pm uninstall -k --user 0 com.android.protips
adb.exe shell pm uninstall -k --user 0 com.android.dynsystem
adb.exe shell pm uninstall -k --user 0 com.android.inputmethod.latin
adb.exe shell pm uninstall -k --user 0 com.android.camera2
adb.exe shell pm uninstall -k --user 0 com.android.providers.partnerbookmar
adb.exe shell pm uninstall -k --user 0 com.android.emergency
adb.exe shell pm uninstall -k --user 0 com.android.printspooler
adb.exe shell pm uninstall -k --user 0 com.android.apps.tag
adb.exe shell pm uninstall -k --user 0 com.android.dreams.basic
adb.exe shell pm uninstall -k --user 0 com.android.dreams.phototable
adb.exe shell pm uninstall -k --user 0 com.android.magicsmoke
adb.exe shell pm uninstall -k --user 0 com.android.managedprovisioning
adb.exe shell pm uninstall -k --user 0 com.android.noisefield
adb.exe shell pm uninstall -k --user 0 com.android.phasebeam
adb.exe shell pm uninstall -k --user 0 com.android.wallpaper.holospiral
adb.exe shell pm uninstall -k --user 0 com.android.stk
adb.exe shell pm uninstall -k --user 0 com.android.bluetoothmidiservice
adb.exe shell pm uninstall -k --user 0 com.android.browser
adb.exe shell pm uninstall -k --user 0 com.android.cellbroadcastreciever
adb.exe shell pm uninstall -k --user 0 com.android.hotwordenrollment.okgoog
adb.exe shell pm uninstall -k --user 0 com.android.printservice.recommendat
adb.exe shell pm uninstall -k --user 0 com.android.quicksearchbox
adb.exe shell pm uninstall -k --user 0 com.android.email
adb.exe shell pm uninstall -k --user 0 com.android.bips
adb.exe shell pm uninstall -k --user 0 com.android.hotwordenrollment.xgoogl
adb.exe shell pm uninstall -k --user 0 com.android.chrome
adb.exe shell pm uninstall -k --user 0 com.android.calendar
adb.exe shell pm uninstall -k --user 0 com.android.providers.calendar
adb.exe shell pm uninstall -k --user 0 android.romstats
adb.exe shell pm uninstall -k --user 0 com.android.documentsui
adb.exe shell pm uninstall -k --user 0 com.android.globalFileexplorer
adb.exe shell pm uninstall -k --user 0 com.android.midrive
adb.exe shell pm uninstall -k --user 0 com.android.calculator2
adb.exe shell pm uninstall -k --user 0 com.android.soundrecorder
adb.exe shell pm uninstall -k --user 0 com.android.musicfx
adb.exe shell pm uninstall -k --user 0 com.android.bookmarkprovider
adb.exe shell pm uninstall -k --user 0 com.android.gallery3d
adb.exe shell pm uninstall -k --user 0 com.android.calllogbackup
adb.exe shell pm uninstall -k --user 0 com.android.traceur
adb.exe shell pm uninstall -k --user 0 com.sec.android.AutoPreconfig
adb.exe shell pm uninstall -k --user 0 com.sec.android.service.health 
adb.exe shell pm uninstall -k --user 0 com.google.android.tts
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.googleassist
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.maps
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.setupwizard.
adb.exe shell pm uninstall -k --user 0 com.google.android.pixel.setupwizard
adb.exe shell pm uninstall -k --user 0 com.google.android.gm
adb.exe shell pm uninstall -k --user 0 com.google.android.calendar
adb.exe shell pm uninstall -k --user 0 com.google.android.calculator
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.recorder
adb.exe shell pm uninstall -k --user 0 com.google.android.printservice.reco
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.books
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.cloudprint
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.currents
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.fitness
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.photos
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.plus
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.tachyon
adb.exe shell pm uninstall -k --user 0 com.google.android.music
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.wellbeing
adb.exe shell pm uninstall -k --user 0 com.google.android.email
adb.exe shell pm uninstall -k --user 0 com.google.android.googlequicksearch
adb.exe shell pm uninstall -k --user 0 com.google.android.talk
adb.exe shell pm uninstall -k --user 0 com.google.android.syncadapters.cont
adb.exe shell pm uninstall -k --user 0 com.google.android.videos
adb.exe shell pm uninstall -k --user 0 com.google.tango.measure
adb.exe shell pm uninstall -k --user 0 com.google.android.youtube
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.docs
adb.exe shell pm uninstall -k --user 0 com.google.ar.lens
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.restore
adb.exe shell pm uninstall -k --user 0 com.google.android.soundpicker
adb.exe shell pm uninstall -k --user 0 com.google.android.syncadapters.cale
adb.exe shell pm uninstall -k --user 0 com.google.ar.core
adb.exe shell pm uninstall -k --user 0 com.google.android.setupwizard
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.wallpaper
adb.exe shell pm uninstall -k --user 0 com.google.android.projection.gearhe
adb.exe shell pm uninstall -k --user 0 com.google.android.marvin.talkback
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.magazines
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.subscription
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.podcasts
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.turbo
adb.exe shell pm uninstall -k --user 0 com.google.android.as
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.youtube.musi
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.nbu.files
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.walletnfcrel
adb.exe shell pm uninstall -k --user 0 com.vivo.browser
adb.exe shell pm uninstall -k --user 0 com.facebook.katana
adb.exe shell pm uninstall -k --user 0 com.facebook.system
adb.exe shell pm uninstall -k --user 0 com.facebook.appmanager
adb.exe shell pm uninstall -k --user 0 com.facebook.services
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.subscriptions.red
adb.exe shell pm uninstall -k --user 0 com.vivo.appstore
adb.exe shell pm uninstall -k --user 0 com.vivo.weather
adb.exe shell pm uninstall -k --user 0 com.vivo.weather.provider
adb.exe shell pm uninstall -k --user 0 com.google.android.apps.youtube.music
adb.exe shell pm uninstall -k --user 0 com.vivo.easyshare
adb.exe shell pm uninstall -k --user 0 com.vivo.calculator
adb.exe shell pm uninstall -k --user 0 com.vivo.imanager
adb.exe shell pm uninstall -k --user 0 com.vivo.share
adb.exe shell pm uninstall -k --user 0 com.netflix.mediaclient
adb.exe shell pm uninstall -k --user 0 com.bbk.cloud
adb.exe shell service call package 131 s16 com.vivo.appstore i32 0 i32 0
ech.exeo "Install gboard"
echo "you need to allow to install"
adb.exe install gb.apk
echo done
pause
